name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Iniciar sesión en DockerHub (si lo necesitas)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Construir la imagen de Docker
      - name: Build Docker Image
        run: |
          docker build \
            --build-arg DB_HOST=${{ secrets.DB_HOST }} \
            --build-arg DB_DATABASE=${{ secrets.DB_DATABASE }} \
            --build-arg DB_USER=${{ secrets.DB_USER }} \
            --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --build-arg TOKEN_SECRET=${{ secrets.TOKEN_SECRET }} \
            -t your-backend-image-name .

      # 4. Subir la imagen a DockerHub (opcional)
      - name: Push Docker Image
        run: |
          docker tag backend-taller3 ${{ secrets.DOCKER_USERNAME }}/backend-taller3
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-taller3
